import type { NextPage } from 'next';
import { getImageSize } from 'next/dist/server/image-optimizer';
import Head from 'next/head';
import Image from 'next/image';
import { getImages } from '../database/get_images';
import { homeImageProps } from '../interfaces/interfaces';
import styles from '../styles/Home.module.scss';

const Home: NextPage<{images: {id: number, url: string}[]}> = ({images}) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Illustrator</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Illustrator</h1>
                <div className={styles.grid}>
                    {images.map((image) => (
                        <HomeImage
                        {...{
                            imageUrl: image.url,
                        }}
                    />
                    )
                    )}
                    
                </div>
            </main>

            <footer className={styles.footer}>
                <a href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app' target='_blank' rel='noopener noreferrer'>
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
};

function HomeImage({ imageUrl }: homeImageProps) {
    return (
        <div className={styles.card}>
            <Image className={styles.homeImage} src={imageUrl} width={100} height={130} />
        </div>
    );
}

export async function getStaticProps() {
    const res = await getImages();
    const images = await res.rows;

    return {
      props: {
          images
      },
    }
  }

export default Home;
